[server]
maxUploadSize = 5000
enableXsrfProtection = false
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

# Importante: Aumentar timeouts
[runner]
fastReruns = false